Repository prgrms-fe-devcourse/FEDC4_CUCUMIS_Pocojang, pull requests merged in 2023-09, with the labels that each got.

#6 pr템플릿 추가
  .github/pull_request_template.md
Labels: 문서

#8 Feature/4 api setup
  .gitignore
  api/cucumis.ts
  package-lock.json
  package.json
  src/consts/api.ts
  src/utils/api.ts
Labels: 기능

#10 Feature/2 global styles
  index.html
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  src/styles/index.css
  src/styles/theme.ts
Labels: 스타일

#7 Feature/1 router
  package-lock.json
  package.json
  src/App.tsx
  src/components/header/index.tsx
  src/components/layout/HeaderLayout.tsx
  src/components/layout/RootLayout.tsx
  src/components/nav/index.tsx
  src/pages/developers/[developerId].tsx
  src/pages/developers/index.tsx
  src/pages/dm/[dmId].tsx
  src/pages/dm/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/notFound/index.tsx
  src/pages/notification/index.tsx
  src/pages/profile/index.tsx
  src/pages/projects/[projectId].tsx
  src/pages/projects/index.tsx
  src/pages/projects/write/[writeId].tsx
  src/pages/projects/write/index.tsx
  src/pages/settings/index.tsx
  src/pages/signup/step1.tsx
  src/pages/signup/step2.tsx
  src/routes/appRouter.tsx
Labels: 기능

#18 Feature/17 chip component
  src/components/shared/chip/index.tsx
  src/components/shared/chipGroup/index.tsx
Labels: 기능

#19 Feature/9 rtk setup
  package-lock.json
  package.json
  src/stores/auth/index.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/stores/hooks.ts
  src/stores/index.ts
  src/stores/layout/index.ts
  src/stores/layout/listener.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/stores/listenerMiddleware.ts
  src/stores/listeners.ts
  src/stores/reducers.ts
Labels: 기능

#34 Feature/21 authStore 및 layoutStore 추가
  src/App.tsx
  src/api/auth/login.ts
  src/api/auth/signup.ts
  src/components/layout/RootLayout.tsx
  src/consts/sessionStorage.ts
  src/stores/auth/index.ts
  src/stores/auth/listener.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/stores/index.ts
  src/stores/layout/index.ts
  src/stores/layout/listener.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/stores/listenerMiddleware.ts
  src/stores/listeners.ts
  src/stores/reducers.ts
  src/types/api/login/index.ts
  src/types/api/signup/index.ts
  src/types/request/body/LoginType.ts
  src/types/request/body/SignupType.ts
  src/types/response/LoginType.ts
  src/types/response/SignupType.ts
  src/utils/api.ts
  src/utils/layout.ts
  src/utils/sessionStorage.ts
Labels: 기능

#25 Feature/24 Avatar 컴포넌트 구현
  public/Logo96.svg
  src/components/shared/avatar/index.tsx
  src/types/components/BasicAvatarProps.ts
Labels: 기능

#36 Feature/35 RootLayout 안에 404 페이지 보이는 기능 추가
  src/App.tsx
  src/components/layout/RootLayout.tsx
  src/routes/appRouter.tsx
  src/routes/index.tsx
Labels: 기능

#41 Feature/37 avatarWithChip 컴포넌트 구현
  src/components/shared/avatarWithChip/index.tsx
Labels: 기능

#26 BasicFab component 구현
  src/components/shared/fab/index.tsx
Labels: 기능

#46 Feature/38 cardComponent 구현
  src/components/shared/card/index.tsx
  src/components/shared/developerCard/index.tsx
  src/components/shared/projectCard/index.tsx
Labels: 기능

#33 기본 버튼 구현
  .prettierrc
  package-lock.json
  package.json
  src/components/shared/button/index.tsx
  src/components/shared/iconButton/index.tsx
Labels: 기능

#51 Feature/12 navbar component
  src/api/channels/create/index.ts
  src/api/channels/index.ts
  src/api/login/index.ts
  src/api/search/all/index.ts
  src/api/search/users/index.ts
  src/api/settings/updatePassword/index.ts
  src/api/signup/index.ts
  src/components/layout/RootLayout.tsx
  src/components/nav/index.tsx
  src/components/navbar/index.tsx
  src/hooks/useAuth.tsx
  src/stores/auth/index.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/stores/index.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/types/api/authUser/RequestAuthUserType.ts
  src/types/api/channel/channelName/ResponseChannelName.ts
  src/types/api/channels/ResponseChannelType.ts
  src/types/api/channels/create/RequestChannelType.ts
  src/types/api/comments/create/RequestBodyCommentsType.ts
  src/types/api/comments/create/RequestHeaderCommentsType.ts
  src/types/api/comments/delete/RequestBodyDeleteCommentsType.ts
  src/types/api/follow/create/RequestBodyCreateFollowType.ts
  src/types/api/follow/delete/ReqeustHeaderDeleteFollowType.ts
  src/types/api/follow/delete/RequestBodyDeleteFollowType.ts
  src/types/api/follow/delete/ResponseDeleteFollowType.ts
  src/types/api/likes/create/RequestBodyLikesType.ts
  src/types/api/likes/create/RequestHeaderLikesType.ts
  src/types/api/likes/create/ResponseLikesType.ts
  src/types/api/likes/delete/RequestBodyDeleteLikesType.ts
  src/types/api/likes/delete/ResponseDeleteLikesType.ts
  src/types/api/login/RequestLoginType.ts
  src/types/api/login/ResponseLoginType.ts
  src/types/api/login/index.ts
  src/types/api/messages/ReqeustHeaderMessagesType.ts
  src/types/api/messages/RequestParamsMessagesType.ts
  src/types/api/messages/create/ReqeustHeaderCreateMessagesType.ts
  src/types/api/messages/create/RequestBodyCreateMessagesType.ts
  src/types/api/messages/updateSeen/RequestBodyUpdateMessagesType.ts
  src/types/api/notifications/create/RequestBodyCreateNotificationType.ts
  src/types/api/notifications/create/ResponseCreateNotificationType.ts
  src/types/api/posts/author/authorId/ResponseAuthorIdType.ts
  src/types/api/posts/delete/RequestBodyDeletePostType.ts
  src/types/api/posts/postId/ResponsePostIdType.ts
  src/types/api/posts/update/RequestBodyPostUpdateType.ts
  src/types/api/search/all/ResponseSearchAllType.ts
  src/types/api/settings/updatePassword/RequestBodyUpdatePwType.ts
  src/types/api/settings/updateUser/RequestBodyUpdateUserType.ts
  src/types/api/signup/RequestSignupType.ts
  src/types/api/signup/index.ts
  src/types/api/users/userId/ResponseUserIdType.ts
Labels: 기능

#49 Feature/42 itemwithavatar component
  src/components/shared/itemWithAvatar/index.tsx
  src/types/components/ItemWithAvatarProps.ts
Labels: 기능

#60 Hotfix/59 useForm hook
  src/components/shared/input/index.tsx
  src/components/shared/search/index.tsx
  src/hooks/components/useForm.ts
  src/hooks/components/useInput.ts
  src/types/components/BasicInputProps.ts
Labels: 버그

#63 Feature/20 header component
  public/assets/Logo512.png
  src/components/header/index.tsx
  src/components/layout/HeaderLayout.tsx
  src/components/layout/RootLayout.tsx
  src/components/navbar/index.tsx
  src/components/shared/search/index.tsx
  src/stores/auth/index.ts
  src/stores/auth/slice.ts
  src/stores/layout/index.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/types/components/Header.ts
  src/utils/layout.ts
Labels: 기능

#72 20230912 deploy
  public/assets/Logo512.png
  src/components/header/index.tsx
  src/components/layout/HeaderLayout.tsx
  src/components/layout/RootLayout.tsx
  src/components/navbar/index.tsx
  src/components/shared/input/index.tsx
  src/components/shared/search/index.tsx
  src/hooks/components/useForm.ts
  src/hooks/components/useInput.ts
  src/stores/auth/index.ts
  src/stores/auth/slice.ts
  src/stores/layout/index.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/types/components/BasicInputProps.ts
  src/types/components/Header.ts
  src/utils/layout.ts
Labels: 배포

#69 Feature/52 signup page
  src/assets/logo/cucumis-logo.svg
  src/components/shared/input/index.tsx
  src/components/signup/signupInputContainer.tsx
  src/hooks/components/useForm.ts
  src/pages/signup/step1.tsx
  src/pages/signup/step2.tsx
  src/utils/validations.ts
Labels: 기능

#80 Feature/61 project list page
  src/components/ProjectList/useProjectList.ts
  src/components/shared/card/index.tsx
  src/components/shared/projectCard/index.tsx
  src/pages/projects/index.tsx
Labels: 기능

#78 Feature/65 dm list page
  src/components/dm/useDMList.ts
  src/components/shared/itemWithAvatar/index.tsx
  src/pages/dm/index.tsx
Labels: 기능

#79 feature/76 project post page
  package-lock.json
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/pages/projects/write/[writeId].tsx
  src/pages/projects/write/index.tsx
Labels: 기능

#85 Feature/56 project details page
  public/assets/Logo96.svg
  src/components/comments/index.tsx
  src/components/projects/useProjectDetail.ts
  src/components/shared/avatar/index.tsx
  src/consts/routes.ts
  src/pages/projects/[projectId].tsx
Labels: 기능

#81 Feature/68 developer details page
  src/components/comments/index.tsx
  src/components/developers/useDeveloperDetail.ts
  src/consts/routes.ts
  src/pages/developers/[developerId].tsx
Labels: 기능

#86 Feature/73 dm detail page
  src/components/dm/message.tsx
  src/components/dm/useDMDetail.ts
  src/pages/dm/[dmId].tsx
Labels: 기능

#87 Feature/75 로그인, 회원가입 step1 까지 기능 완성
  api/cucumis.ts
  src/api/auth/signup.ts
  src/components/login/useLoginForm.ts
  src/components/signup/useExtraInformationForm.ts
  src/components/signup/useSignupForm.ts
  src/consts/sessionStorage.ts
  src/hooks/components/useForm.ts
  src/hooks/useAuth.ts
  src/hooks/useAuth.tsx
  src/pages/login/index.tsx
  src/pages/signup/step1.tsx
  src/pages/signup/step2.tsx
  src/stores/auth/index.ts
  src/stores/auth/listener.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/utils/validations.ts
Labels: 기능

#83 Feature/55 notification page
  src/components/notification/NotificationItem.tsx
  src/components/notification/useNotification.ts
  src/pages/notification/index.tsx
Labels: 기능

#90 Feature/84 home page
  src/components/home/useHome.ts
  src/pages/index.tsx
Labels: 기능

#91 20230913 deploy
  api/cucumis.ts
  package-lock.json
  public/assets/Logo96.svg
  src/api/auth/signup.ts
  src/api/search/all/index.ts
  src/api/search/users/index.ts
  src/assets/logo/cucumis-logo.svg
  src/components/ProjectList/useProjectList.ts
  src/components/comments/index.tsx
  src/components/developers/useDeveloperDetail.ts
  src/components/developers/useDevelopers.ts
  src/components/dm/message.tsx
  src/components/dm/useDMDetail.ts
  src/components/dm/useDMList.ts
  src/components/home/useHome.ts
  src/components/login/loginInputContainer.tsx
  src/components/login/useLoginForm.ts
  src/components/notification/NotificationItem.tsx
  src/components/notification/useNotification.ts
  src/components/profile/bgProfile/index.tsx
  src/components/profile/useProfile.ts
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/components/projects/useProjectDetail.ts
  src/components/shared/avatar/index.tsx
  src/components/shared/card/index.tsx
  src/components/shared/developerCard/index.tsx
  src/components/shared/fab/index.tsx
  src/components/shared/input/index.tsx
  src/components/shared/itemWithAvatar/index.tsx
  src/components/shared/mainFab/index.tsx
  src/components/shared/projectCard/index.tsx
  src/components/signup/signupInputContainer.tsx
  src/components/signup/useExtraInformationForm.ts
  src/components/signup/useSignupForm.ts
  src/consts/routes.ts
  src/consts/sessionStorage.ts
  src/hooks/components/useForm.ts
  src/hooks/useAuth.ts
  src/hooks/useAuth.tsx
  src/pages/developers/[developerId].tsx
  src/pages/developers/index.tsx
  src/pages/dm/[dmId].tsx
  src/pages/dm/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/notification/index.tsx
  src/pages/profile/index.tsx
  src/pages/projects/[projectId].tsx
  src/pages/projects/index.tsx
  src/pages/projects/write/[writeId].tsx
  src/pages/projects/write/index.tsx
  src/pages/settings/index.tsx
  src/pages/signup/step1.tsx
  src/pages/signup/step2.tsx
  src/stores/auth/index.ts
  src/stores/auth/listener.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/utils/validations.ts
Labels: 배포

#93 Hotfix/73 message component error
  src/components/dm/message.tsx
Labels: 버그

#94 Hotfix/simplify hooks folder
  public/Logo96.svg
  src/components/header/index.tsx
  src/components/login/useLoginForm.ts
  src/components/navbar/index.tsx
  src/components/shared/avatar/index.tsx
  src/components/signup/useExtraInformationForm.ts
  src/components/signup/useSignupForm.ts
  src/hooks/useForm.ts
Labels: 리팩토링

#96 refactor : 안쓰는 e => _로 변경
  src/pages/profile/index.tsx
Labels: 버그

#102 feature: .nvmrc 추가
  .nvmrc
Labels: 기능

#105 utils API 모듈 header 에 session storage 에서 token 가져오는 기능 추가
  src/utils/api.ts
Labels: 기능

#108 fix: session storage util import 수정
  src/utils/api.ts
Labels: 버그

#109 20230914 deploy
  .nvmrc
  package-lock.json
  src/utils/api.ts
Labels: 배포

#111 Feature/110 layoutstore input useform
  src/components/header/index.tsx
  src/components/navbar/index.tsx
  src/hooks/useForm.ts
  src/stores/layout/index.ts
  src/stores/layout/selector.ts
Labels: 기능

#99 infiniteScroll hook 추가
  src/hooks/useInfiniteScroll.ts
Labels: 기능

#114 Feature/113 axios api multi form
  api/cucumis.ts
  package-lock.json
  package.json
  src/api/users/uploadPhoto/index.ts
  src/types/models/FormType.ts
  src/utils/api.ts
Labels: 기능

#112 Feature/107 signup page extra input
  src/components/signup/useExtraInformationForm.ts
  src/components/signup/useSignupForm.ts
  src/consts/channels.ts
  src/pages/signup/step1.tsx
  src/pages/signup/step2.tsx
  src/stores/auth/index.ts
  src/stores/auth/selector.ts
  src/stores/reducers.ts
  src/stores/signup/index.ts
  src/stores/signup/selector.ts
  src/stores/signup/slice.ts
  src/types/models/UserType.ts
Labels: 기능

#119 Feature/98 profile page navigation
  src/components/profile/profileNav/index.tsx
  src/components/profile/useProfile.ts
  src/pages/profile/index.tsx
Labels: 기능

#122 Feature/120 profile follow unfollow
  src/pages/profile/index.tsx
Labels: 기능

#127 Feature/100 dm detail page
  src/api/messages/index.ts
  src/components/dm/message.tsx
  src/components/dm/useDMDetail.ts
  src/hooks/useInterval.ts
  src/pages/dm/[dmId].tsx
  src/stores/dm/index.ts
  src/stores/dm/selector.ts
  src/stores/dm/slice.ts
  src/stores/layout/index.ts
  src/stores/layout/selector.ts
  src/stores/layout/slice.ts
  src/stores/reducers.ts
  src/utils/layout.ts
Labels: 기능

#124 Feature/95 project developer page
  src/components/comments/index.tsx
  src/components/comments/useComment.ts
  src/components/developers/useDeveloperDetail.ts
  src/components/projects/useProjectDetail.ts
  src/components/shared/itemWithAvatar/index.tsx
  src/consts/routes.ts
  src/pages/developers/[developerId].tsx
  src/pages/projects/[projectId].tsx
  src/stores/projectDetail/index.ts
  src/stores/projectDetail/selector.ts
  src/stores/projectDetail/slice.ts
  src/stores/reducers.ts
  src/types/api/follow/index.ts
  src/types/components/ItemWithAvatarProps.ts
  src/types/index.ts
  src/types/models/CommentType.ts
  src/types/models/PostType.ts
  src/types/models/UserType.ts
Labels: 기능

#128 Feature/115 project modify page
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/pages/profile/index.tsx
  src/types/models/UserType.ts
Labels: 기능

#129 Feature/104 notificaiton page
  src/components/notification/NotificationItem.tsx
  src/components/notification/useNotification.ts
  src/pages/notification/index.tsx
  src/stores/notification/index.ts
  src/stores/notification/selector.ts
  src/stores/notification/slice.ts
  src/stores/reducers.ts
Labels: 기능

#136 Feature/89 dm list page
  src/components/dm/useDMDetail.ts
  src/components/dm/useDMList.ts
  src/components/shared/itemWithAvatar/index.tsx
  src/pages/dm/index.tsx
  src/stores/dm/index.ts
  src/stores/dm/selector.ts
  src/stores/dm/slice.ts
Labels: 기능

#134 Feature/117 developers page
  src/components/developers/useDevelopers.ts
  src/components/shared/developerCard/index.tsx
  src/pages/developers/index.tsx
  src/pages/profile/index.tsx
  src/stores/developers/index.ts
  src/stores/developers/selector.ts
  src/stores/developers/slice.ts
  src/stores/reducers.ts
Labels: 기능

#144 Refactor/139 project detail page
  src/components/projects/useProjectDetail.ts
  src/pages/projects/[projectId].tsx
Labels: 리팩토링

#132 Feature/116 projects page
  src/components/ProjectList/useProjectList.ts
  src/pages/projects/index.tsx
  src/stores/projects/index.ts
  src/stores/projects/selector.ts
  src/stores/projects/slice.ts
  src/stores/reducers.ts
Labels: 기능

#152 Refactor/146 developer detail page
  src/components/developers/useDeveloperDetail.ts
  src/pages/developers/[developerId].tsx
  src/stores/auth/selector.ts
Labels: 리팩토링

#154 Hotfix/140 dm scroll
  src/components/dm/useDMDetail.ts
Labels: 버그

#155 Feature/142 search developers
  src/components/developers/useDevelopers.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/developers/index.tsx
  src/stores/developers/index.ts
  src/stores/developers/selector.ts
  src/stores/developers/slice.ts
Labels: 기능

#157 Refactor/153 project modify page
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/consts/formDataKey.ts
Labels: 리팩토링

#166 Hotfix/162 project detail page exception handling
  src/components/comments/useComment.ts
  src/components/projects/useProjectDetail.ts
  src/consts/routes.ts
  src/pages/notFound/index.tsx
  src/pages/projects/[projectId].tsx
  src/utils/axiosError.ts
Labels: 버그

#167 Hotfix/165 developer detail page exception handling
  src/components/developers/useDeveloperDetail.ts
  src/pages/developers/[developerId].tsx
Labels: 버그

#169 Hotfix/168-project modify page exception handling
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
Labels: 버그

#159 Feature/133 settings profile
  src/components/header/index.tsx
  src/components/settings/SettingsInputContainer.tsx
  src/components/settings/password/useSettingsPasswordForm.ts
  src/components/settings/profile/useSettingsProfileForm.ts
  src/components/signup/useExtraInformationForm.ts
  src/hooks/useAuth.ts
  src/pages/login/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/password/index.tsx
  src/pages/settings/profile/index.tsx
  src/pages/signup/step1.tsx
  src/routes/index.tsx
  src/stores/auth/index.ts
  src/stores/auth/listener.ts
  src/stores/auth/selector.ts
  src/stores/auth/slice.ts
  src/stores/reducers.ts
  src/stores/settings/profile/index.ts
  src/stores/settings/profile/selector.ts
  src/stores/settings/profile/slice.ts
  src/types/components/Header.ts
  src/utils/layout.ts
  src/utils/sessionStorage.ts
Labels: 기능

#164 Feature/161 profile setting oneliner
  src/components/settings/profile/useSettingsProfileForm.ts
  src/pages/settings/profile/index.tsx
  src/pages/signup/step2.tsx
Labels: 리팩토링

#160 Feature/156 notification refactor
  src/components/notification/useNotification.ts
  src/consts/notificationCreateType.ts
  src/pages/notification/index.tsx
  src/stores/notification/index.ts
  src/stores/notification/slice.ts
Labels: 리팩토링

#176 Feature/170 project developer detail page extra
  src/components/comments/useComment.ts
  src/components/developers/useDeveloperDetail.ts
  src/components/header/index.tsx
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/components/projects/useProjectDetail.ts
  src/components/shared/fullLineTyphograhy/index.tsx
  src/components/shared/itemWithAvatar/index.tsx
  src/components/shared/likes/index.tsx
  src/pages/developers/[developerId].tsx
  src/pages/projects/[projectId].tsx
  src/stores/projectDetail/index.ts
  src/stores/projectDetail/selector.ts
  src/stores/projectDetail/slice.ts
  src/types/api/likes/index.ts
Labels: 버그, 기능

#181 Hotfix/180 conversation type
  src/components/dm/useDMList.ts
  src/pages/dm/index.tsx
  src/stores/dm/slice.ts
  src/types/components/ItemWithAvatarProps.ts
Labels: 버그

#178 Feature/173 home page refactor
  src/components/ProjectList/useProjectList.ts
  src/components/developers/useDevelopers.ts
  src/components/home/RecommendationCard.tsx
  src/components/home/useHome.ts
  src/components/shared/fixedPorgress/index.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/developers/index.tsx
  src/pages/index.tsx
  src/pages/projects/index.tsx
  src/stores/developers/index.ts
  src/stores/developers/slice.ts
  src/stores/projects/index.ts
  src/stores/projects/selector.ts
  src/stores/projects/slice.ts
Labels: 리팩토링

#171 Feature/163 projects refactor
  src/hooks/useInfiniteScroll.ts
Labels: 리팩토링

#182 Feature/151 profile refactor
  src/components/profile/navigationProfileContent/index.tsx
  src/components/profile/profileChangeButton/index.tsx
  src/components/profile/useProfile.ts
  src/components/profile/useProfile.tsx
  src/pages/profile/index.tsx
  src/stores/profile/index.ts
  src/stores/profile/selector.ts
  src/stores/profile/slice.ts
  src/stores/reducers.ts
Labels: 리팩토링

#190 Hotfix/project detail page all bugs
  src/components/developers/useDeveloperDetail.ts
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/components/projects/useProjectDetail.ts
  src/components/shared/fullLineTyphograhy/index.tsx
  src/consts/routes.ts
  src/pages/developers/[developerId].tsx
  src/pages/projects/[projectId].tsx
  src/stores/projectDetail/slice.ts
Labels: 버그

#192 Hotfix/186 browser tab title favicon
  index.html
  public/favicon.svg
Labels: 버그

#193 20230926 deploy
  index.html
  public/favicon.svg
  src/components/developers/useDeveloperDetail.ts
  src/components/profile/navigationProfileContent/index.tsx
  src/components/profile/useProfile.ts
  src/components/projects/projectPost.tsx
  src/components/projects/usePost.ts
  src/components/projects/useProjectDetail.ts
  src/components/shared/fullLineTyphograhy/index.tsx
  src/consts/routes.ts
  src/pages/developers/[developerId].tsx
  src/pages/projects/[projectId].tsx
  src/stores/projectDetail/slice.ts
Labels: 배포

#197 fix: profile 값을 수정하지 않았을 때, defaultValue 를 가져오지 못하는 버그 수정
  src/components/settings/profile/useSettingsProfileForm.ts
Labels: 버그

#199 fix: profile 수정 시, name 으로 빈 값이 들어가는 에러 수정
  src/components/settings/profile/useSettingsProfileForm.ts
Labels: 버그

#201 Hotfix/twice comments bug
  src/components/comments/useComment.ts
  src/components/shared/likes/index.tsx
  src/stores/auth/index.ts
  src/stores/auth/selector.ts
  src/stores/projectDetail/index.ts
  src/stores/projectDetail/slice.ts
Labels: 버그

#200 docs: README.md 작성
  README.md
Labels: 문서

#202 Hotfix/developer detail page follow optimistic update
  src/components/developers/useDeveloperDetail.ts
  src/components/shared/likes/index.tsx
  src/pages/developers/[developerId].tsx
  src/stores/projectDetail/index.ts
  src/stores/projectDetail/slice.ts
Labels: 버그
